### PR TITLE
Update fields.py

### PR DESCRIPTION
**Pull request by lautarodapin**
New way of accessing queryset of consumer

### CODE REVIEW

**Comment by hishnash** [comment]
Thankyou for spotting this, could you also update the requirements in the setup.py to request channels v3 (and the docs?)

**Comment by lautarodapin** [comment]
Of course. I'm glad to help.

**Comment by hishnash** [comment]
Thankyou for making this update ! I want to add some Github action tests to this repo then will push out a release

**Comment by lautarodapin** [comment]
I don't have much experience with testing.
I'm about to start adding some basic doc to the other repo of djangochannelsrestframework

**Comment by hishnash** [comment]
If you have time to add some docs that would be very helpful thankyou :)

**Pull request merged**
